export const colorGroups = [
  {
    groupTitle: "Brand Colors",
    colors: [
      {
        title: "Blue",
        value: "#2B7FFF",
        textColor: "#ffffff",
        bgColor: "#2B7FFF",
      },
      {
        title: "Dark Blue",
        value: "#1447E6",
        textColor: "#ffffff",
        bgColor: "#1447E6",
      },
      {
        title: "Sky Blue",
        value: "#00A6F4",
        textColor: "#ffffff",
        bgColor: "#00A6F4",
      },
      {
        title: "Orange",
        value: "#FF6900",
        textColor: "#ffffff",
        bgColor: "#FF6900",
      },
      {
        title: "Light Slate",
        value: "#F1F5F9",
        textColor: "#000000",
        bgColor: "#F1F5F9",
      },
    ],
  },
  {
    groupTitle: "Basic Colors",
    colors: [
      {
        title: "White",
        value: "#ffffff",
        textColor: "#000000",
        bgColor: "#ffffff",
      },
      {
        title: "Black",
        value: "#000000",
        textColor: "#ffffff",
        bgColor: "#000000",
      },
      {
        title: "Gray",
        value: "#888888",
        textColor: "#000000",
        bgColor: "#888888",
      },
      {
        title: "Red",
        value: "#ff0000",
        textColor: "#ffffff",
        bgColor: "#ff0000",
      },
      {
        title: "Yellow",
        value: "#ffff00",
        textColor: "#000000",
        bgColor: "#ffff00",
      },
      {
        title: "Green",
        value: "#00ff00",
        textColor: "#000000",
        bgColor: "#00ff00",
      },
      {
        title: "Cyan",
        value: "#00ffff",
        textColor: "#000000",
        bgColor: "#00ffff",
      },
      {
        title: "Blue",
        value: "#0000ff",
        textColor: "#ffffff",
        bgColor: "#0000ff",
      },
      {
        title: "Magenta",
        value: "#ff00ff",
        textColor: "#ffffff",
        bgColor: "#ff00ff",
      },
    ],
  },
  {
    groupTitle: "Bootstrap Colors",
    colors: [
      {
        title: "Blue (Primary)",
        value: "#007bff",
        textColor: "#ffffff",
        bgColor: "#007bff",
      },
      {
        title: "Indigo",
        value: "#6610f2",
        textColor: "#ffffff",
        bgColor: "#6610f2",
      },
      {
        title: "Purple",
        value: "#6f42c1",
        textColor: "#ffffff",
        bgColor: "#6f42c1",
      },
      {
        title: "Pink",
        value: "#e83e8c",
        textColor: "#ffffff",
        bgColor: "#e83e8c",
      },
      {
        title: "Red (Danger)",
        value: "#dc3545",
        textColor: "#ffffff",
        bgColor: "#dc3545",
      },
      {
        title: "Orange",
        value: "#fd7e14",
        textColor: "#000000",
        bgColor: "#fd7e14",
      },
      {
        title: "Yellow (Warning)",
        value: "#ffc107",
        textColor: "#000000",
        bgColor: "#ffc107",
      },
      {
        title: "Green (Success)",
        value: "#28a745",
        textColor: "#000000",
        bgColor: "#28a745",
      },
      {
        title: "Teal",
        value: "#20c997",
        textColor: "#000000",
        bgColor: "#20c997",
      },
      {
        title: "Cyan (Info)",
        value: "#17a2b8",
        textColor: "#ffffff",
        bgColor: "#17a2b8",
      },
      {
        title: "100 (Light)",
        value: "#f8f9fa",
        textColor: "#000000",
        bgColor: "#f8f9fa",
      },
      {
        title: "200",
        value: "#e9ecef",
        textColor: "#000000",
        bgColor: "#e9ecef",
      },
      {
        title: "300",
        value: "#dee2e6",
        textColor: "#000000",
        bgColor: "#dee2e6",
      },
      {
        title: "400",
        value: "#ced4da",
        textColor: "#000000",
        bgColor: "#ced4da",
      },
      {
        title: "500",
        value: "#adb5bd",
        textColor: "#000000",
        bgColor: "#adb5bd",
      },
      {
        title: "600 (Secondary)",
        value: "#6c757d",
        textColor: "#ffffff",
        bgColor: "#6c757d",
      },
      {
        title: "700",
        value: "#495057",
        textColor: "#ffffff",
        bgColor: "#495057",
      },
      {
        title: "800",
        value: "#343a40",
        textColor: "#ffffff",
        bgColor: "#343a40",
      },
      {
        title: "900 (Dark)",
        value: "#212529",
        textColor: "#ffffff",
        bgColor: "#212529",
      },
    ],
  },
  {
    groupTitle: "Tailwind CSS Colors",
    colors: [
      {
        title: "Red 50",
        value: "#fef2f2",
        textColor: "#000000",
        bgColor: "#fef2f2",
      },
      {
        title: "Red 100",
        value: "#fee2e2",
        textColor: "#000000",
        bgColor: "#fee2e2",
      },
      {
        title: "Red 200",
        value: "#fecaca",
        textColor: "#000000",
        bgColor: "#fecaca",
      },
      {
        title: "Red 300",
        value: "#fca5a5",
        textColor: "#000000",
        bgColor: "#fca5a5",
      },
      {
        title: "Red 400",
        value: "#f87171",
        textColor: "#000000",
        bgColor: "#f87171",
      },
      {
        title: "Red 500",
        value: "#ef4444",
        textColor: "#ffffff",
        bgColor: "#ef4444",
      },
      {
        title: "Red 600",
        value: "#dc2626",
        textColor: "#ffffff",
        bgColor: "#dc2626",
      },
      {
        title: "Red 700",
        value: "#b91c1c",
        textColor: "#ffffff",
        bgColor: "#b91c1c",
      },
      {
        title: "Red 800",
        value: "#991b1b",
        textColor: "#ffffff",
        bgColor: "#991b1b",
      },
      {
        title: "Red 900",
        value: "#7f1d1d",
        textColor: "#ffffff",
        bgColor: "#7f1d1d",
      },
      {
        title: "Red 950",
        value: "#450a0a",
        textColor: "#ffffff",
        bgColor: "#450a0a",
      },
      {
        title: "Orange 50",
        value: "#fff7ed",
        textColor: "#000000",
        bgColor: "#fff7ed",
      },
      {
        title: "Orange 100",
        value: "#ffedd5",
        textColor: "#000000",
        bgColor: "#ffedd5",
      },
      {
        title: "Orange 200",
        value: "#fed7aa",
        textColor: "#000000",
        bgColor: "#fed7aa",
      },
      {
        title: "Orange 300",
        value: "#fdba74",
        textColor: "#000000",
        bgColor: "#fdba74",
      },
      {
        title: "Orange 400",
        value: "#fb923c",
        textColor: "#000000",
        bgColor: "#fb923c",
      },
      {
        title: "Orange 500",
        value: "#f97316",
        textColor: "#ffffff",
        bgColor: "#f97316",
      },
      {
        title: "Orange 600",
        value: "#ea580c",
        textColor: "#ffffff",
        bgColor: "#ea580c",
      },
      {
        title: "Orange 700",
        value: "#c2410c",
        textColor: "#ffffff",
        bgColor: "#c2410c",
      },
      {
        title: "Orange 800",
        value: "#9a3412",
        textColor: "#ffffff",
        bgColor: "#9a3412",
      },
      {
        title: "Orange 900",
        value: "#7c2d12",
        textColor: "#ffffff",
        bgColor: "#7c2d12",
      },
      {
        title: "Orange 950",
        value: "#431407",
        textColor: "#ffffff",
        bgColor: "#431407",
      },
      {
        title: "Amber 50",
        value: "#fffbeb",
        textColor: "#000000",
        bgColor: "#fffbeb",
      },
      {
        title: "Amber 100",
        value: "#fef3c7",
        textColor: "#000000",
        bgColor: "#fef3c7",
      },
      {
        title: "Amber 200",
        value: "#fde68a",
        textColor: "#000000",
        bgColor: "#fde68a",
      },
      {
        title: "Amber 300",
        value: "#fcd34d",
        textColor: "#000000",
        bgColor: "#fcd34d",
      },
      {
        title: "Amber 400",
        value: "#fbbf24",
        textColor: "#000000",
        bgColor: "#fbbf24",
      },
      {
        title: "Amber 500",
        value: "#f59e0b",
        textColor: "#000000",
        bgColor: "#f59e0b",
      },
      {
        title: "Amber 600",
        value: "#d97706",
        textColor: "#ffffff",
        bgColor: "#d97706",
      },
      {
        title: "Amber 700",
        value: "#b45309",
        textColor: "#ffffff",
        bgColor: "#b45309",
      },
      {
        title: "Amber 800",
        value: "#92400e",
        textColor: "#ffffff",
        bgColor: "#92400e",
      },
      {
        title: "Amber 900",
        value: "#78350f",
        textColor: "#ffffff",
        bgColor: "#78350f",
      },
      {
        title: "Amber 950",
        value: "#451a03",
        textColor: "#ffffff",
        bgColor: "#451a03",
      },
      {
        title: "Yellow 50",
        value: "#fefce8",
        textColor: "#000000",
        bgColor: "#fefce8",
      },
      {
        title: "Yellow 100",
        value: "#fef9c3",
        textColor: "#000000",
        bgColor: "#fef9c3",
      },
      {
        title: "Yellow 200",
        value: "#fef08a",
        textColor: "#000000",
        bgColor: "#fef08a",
      },
      {
        title: "Yellow 300",
        value: "#fde047",
        textColor: "#000000",
        bgColor: "#fde047",
      },
      {
        title: "Yellow 400",
        value: "#facc15",
        textColor: "#000000",
        bgColor: "#facc15",
      },
      {
        title: "Yellow 500",
        value: "#eab308",
        textColor: "#000000",
        bgColor: "#eab308",
      },
      {
        title: "Yellow 600",
        value: "#ca8a04",
        textColor: "#ffffff",
        bgColor: "#ca8a04",
      },
      {
        title: "Yellow 700",
        value: "#a16207",
        textColor: "#ffffff",
        bgColor: "#a16207",
      },
      {
        title: "Yellow 800",
        value: "#854d0e",
        textColor: "#ffffff",
        bgColor: "#854d0e",
      },
      {
        title: "Yellow 900",
        value: "#713f12",
        textColor: "#ffffff",
        bgColor: "#713f12",
      },
      {
        title: "Yellow 950",
        value: "#422006",
        textColor: "#ffffff",
        bgColor: "#422006",
      },
      {
        title: "Lime 50",
        value: "#f7fee7",
        textColor: "#000000",
        bgColor: "#f7fee7",
      },
      {
        title: "Lime 100",
        value: "#ecfccb",
        textColor: "#000000",
        bgColor: "#ecfccb",
      },
      {
        title: "Lime 200",
        value: "#d9f99d",
        textColor: "#000000",
        bgColor: "#d9f99d",
      },
      {
        title: "Lime 300",
        value: "#bef264",
        textColor: "#000000",
        bgColor: "#bef264",
      },
      {
        title: "Lime 400",
        value: "#a3e635",
        textColor: "#000000",
        bgColor: "#a3e635",
      },
      {
        title: "Lime 500",
        value: "#84cc16",
        textColor: "#000000",
        bgColor: "#84cc16",
      },
      {
        title: "Lime 600",
        value: "#65a30d",
        textColor: "#ffffff",
        bgColor: "#65a30d",
      },
      {
        title: "Lime 700",
        value: "#4d7c0f",
        textColor: "#ffffff",
        bgColor: "#4d7c0f",
      },
      {
        title: "Lime 800",
        value: "#3f6212",
        textColor: "#ffffff",
        bgColor: "#3f6212",
      },
      {
        title: "Lime 900",
        value: "#365314",
        textColor: "#ffffff",
        bgColor: "#365314",
      },
      {
        title: "Lime 950",
        value: "#1a2e05",
        textColor: "#ffffff",
        bgColor: "#1a2e05",
      },
      {
        title: "Green 50",
        value: "#f0fdf4",
        textColor: "#000000",
        bgColor: "#f0fdf4",
      },
      {
        title: "Green 100",
        value: "#dcfce7",
        textColor: "#000000",
        bgColor: "#dcfce7",
      },
      {
        title: "Green 200",
        value: "#bbf7d0",
        textColor: "#000000",
        bgColor: "#bbf7d0",
      },
      {
        title: "Green 300",
        value: "#86efac",
        textColor: "#000000",
        bgColor: "#86efac",
      },
      {
        title: "Green 400",
        value: "#4ade80",
        textColor: "#000000",
        bgColor: "#4ade80",
      },
      {
        title: "Green 500",
        value: "#22c55e",
        textColor: "#000000",
        bgColor: "#22c55e",
      },
      {
        title: "Green 600",
        value: "#16a34a",
        textColor: "#ffffff",
        bgColor: "#16a34a",
      },
      {
        title: "Green 700",
        value: "#15803d",
        textColor: "#ffffff",
        bgColor: "#15803d",
      },
      {
        title: "Green 800",
        value: "#166534",
        textColor: "#ffffff",
        bgColor: "#166534",
      },
      {
        title: "Green 900",
        value: "#14532d",
        textColor: "#ffffff",
        bgColor: "#14532d",
      },
      {
        title: "Green 950",
        value: "#052e16",
        textColor: "#ffffff",
        bgColor: "#052e16",
      },
      {
        title: "Emerald 50",
        value: "#ecfdf5",
        textColor: "#000000",
        bgColor: "#ecfdf5",
      },
      {
        title: "Emerald 100",
        value: "#d1fae5",
        textColor: "#000000",
        bgColor: "#d1fae5",
      },
      {
        title: "Emerald 200",
        value: "#a7f3d0",
        textColor: "#000000",
        bgColor: "#a7f3d0",
      },
      {
        title: "Emerald 300",
        value: "#6ee7b7",
        textColor: "#000000",
        bgColor: "#6ee7b7",
      },
      {
        title: "Emerald 400",
        value: "#34d399",
        textColor: "#000000",
        bgColor: "#34d399",
      },
      {
        title: "Emerald 500",
        value: "#10b981",
        textColor: "#000000",
        bgColor: "#10b981",
      },
      {
        title: "Emerald 600",
        value: "#059669",
        textColor: "#ffffff",
        bgColor: "#059669",
      },
      {
        title: "Emerald 700",
        value: "#047857",
        textColor: "#ffffff",
        bgColor: "#047857",
      },
      {
        title: "Emerald 800",
        value: "#065f46",
        textColor: "#ffffff",
        bgColor: "#065f46",
      },
      {
        title: "Emerald 900",
        value: "#064e3b",
        textColor: "#ffffff",
        bgColor: "#064e3b",
      },
      {
        title: "Emerald 950",
        value: "#022c22",
        textColor: "#ffffff",
        bgColor: "#022c22",
      },
      {
        title: "Teal 50",
        value: "#f0fdfa",
        textColor: "#000000",
        bgColor: "#f0fdfa",
      },
      {
        title: "Teal 100",
        value: "#ccfbf1",
        textColor: "#000000",
        bgColor: "#ccfbf1",
      },
      {
        title: "Teal 200",
        value: "#99f6e4",
        textColor: "#000000",
        bgColor: "#99f6e4",
      },
      {
        title: "Teal 300",
        value: "#5eead4",
        textColor: "#000000",
        bgColor: "#5eead4",
      },
      {
        title: "Teal 400",
        value: "#2dd4bf",
        textColor: "#000000",
        bgColor: "#2dd4bf",
      },
      {
        title: "Teal 500",
        value: "#14b8a6",
        textColor: "#000000",
        bgColor: "#14b8a6",
      },
      {
        title: "Teal 600",
        value: "#0d9488",
        textColor: "#ffffff",
        bgColor: "#0d9488",
      },
      {
        title: "Teal 700",
        value: "#0f766e",
        textColor: "#ffffff",
        bgColor: "#0f766e",
      },
      {
        title: "Teal 800",
        value: "#115e59",
        textColor: "#ffffff",
        bgColor: "#115e59",
      },
      {
        title: "Teal 900",
        value: "#134e4a",
        textColor: "#ffffff",
        bgColor: "#134e4a",
      },
      {
        title: "Teal 950",
        value: "#042f2e",
        textColor: "#ffffff",
        bgColor: "#042f2e",
      },
      {
        title: "Cyan 50",
        value: "#ecfeff",
        textColor: "#000000",
        bgColor: "#ecfeff",
      },
      {
        title: "Cyan 100",
        value: "#cffafe",
        textColor: "#000000",
        bgColor: "#cffafe",
      },
      {
        title: "Cyan 200",
        value: "#a5f3fc",
        textColor: "#000000",
        bgColor: "#a5f3fc",
      },
      {
        title: "Cyan 300",
        value: "#67e8f9",
        textColor: "#000000",
        bgColor: "#67e8f9",
      },
      {
        title: "Cyan 400",
        value: "#22d3ee",
        textColor: "#000000",
        bgColor: "#22d3ee",
      },
      {
        title: "Cyan 500",
        value: "#06b6d4",
        textColor: "#000000",
        bgColor: "#06b6d4",
      },
      {
        title: "Cyan 600",
        value: "#0891b2",
        textColor: "#ffffff",
        bgColor: "#0891b2",
      },
      {
        title: "Cyan 700",
        value: "#0e7490",
        textColor: "#ffffff",
        bgColor: "#0e7490",
      },
      {
        title: "Cyan 800",
        value: "#155e75",
        textColor: "#ffffff",
        bgColor: "#155e75",
      },
      {
        title: "Cyan 900",
        value: "#164e63",
        textColor: "#ffffff",
        bgColor: "#164e63",
      },
      {
        title: "Cyan 950",
        value: "#083344",
        textColor: "#ffffff",
        bgColor: "#083344",
      },
      {
        title: "Sky 50",
        value: "#f0f9ff",
        textColor: "#000000",
        bgColor: "#f0f9ff",
      },
      {
        title: "Sky 100",
        value: "#e0f2fe",
        textColor: "#000000",
        bgColor: "#e0f2fe",
      },
      {
        title: "Sky 200",
        value: "#bae6fd",
        textColor: "#000000",
        bgColor: "#bae6fd",
      },
      {
        title: "Sky 300",
        value: "#7dd3fc",
        textColor: "#000000",
        bgColor: "#7dd3fc",
      },
      {
        title: "Sky 400",
        value: "#38bdf8",
        textColor: "#000000",
        bgColor: "#38bdf8",
      },
      {
        title: "Sky 500",
        value: "#0ea5e9",
        textColor: "#000000",
        bgColor: "#0ea5e9",
      },
      {
        title: "Sky 600",
        value: "#0284c7",
        textColor: "#ffffff",
        bgColor: "#0284c7",
      },
      {
        title: "Sky 700",
        value: "#0369a1",
        textColor: "#ffffff",
        bgColor: "#0369a1",
      },
      {
        title: "Sky 800",
        value: "#075985",
        textColor: "#ffffff",
        bgColor: "#075985",
      },
      {
        title: "Sky 900",
        value: "#0c4a6e",
        textColor: "#ffffff",
        bgColor: "#0c4a6e",
      },
      {
        title: "Sky 950",
        value: "#082f49",
        textColor: "#ffffff",
        bgColor: "#082f49",
      },
      {
        title: "Blue 50",
        value: "#eff6ff",
        textColor: "#000000",
        bgColor: "#eff6ff",
      },
      {
        title: "Blue 100",
        value: "#dbeafe",
        textColor: "#000000",
        bgColor: "#dbeafe",
      },
      {
        title: "Blue 200",
        value: "#bfdbfe",
        textColor: "#000000",
        bgColor: "#bfdbfe",
      },
      {
        title: "Blue 300",
        value: "#93c5fd",
        textColor: "#000000",
        bgColor: "#93c5fd",
      },
      {
        title: "Blue 400",
        value: "#60a5fa",
        textColor: "#000000",
        bgColor: "#60a5fa",
      },
      {
        title: "Blue 500",
        value: "#3b82f6",
        textColor: "#ffffff",
        bgColor: "#3b82f6",
      },
      {
        title: "Blue 600",
        value: "#2563eb",
        textColor: "#ffffff",
        bgColor: "#2563eb",
      },
      {
        title: "Blue 700",
        value: "#1d4ed8",
        textColor: "#ffffff",
        bgColor: "#1d4ed8",
      },
      {
        title: "Blue 800",
        value: "#1e40af",
        textColor: "#ffffff",
        bgColor: "#1e40af",
      },
      {
        title: "Blue 900",
        value: "#1e3a8a",
        textColor: "#ffffff",
        bgColor: "#1e3a8a",
      },
      {
        title: "Blue 950",
        value: "#172554",
        textColor: "#ffffff",
        bgColor: "#172554",
      },
      {
        title: "Indigo 50",
        value: "#eef2ff",
        textColor: "#000000",
        bgColor: "#eef2ff",
      },
      {
        title: "Indigo 100",
        value: "#e0e7ff",
        textColor: "#000000",
        bgColor: "#e0e7ff",
      },
      {
        title: "Indigo 200",
        value: "#c7d2fe",
        textColor: "#000000",
        bgColor: "#c7d2fe",
      },
      {
        title: "Indigo 300",
        value: "#a5b4fc",
        textColor: "#000000",
        bgColor: "#a5b4fc",
      },
      {
        title: "Indigo 400",
        value: "#818cf8",
        textColor: "#000000",
        bgColor: "#818cf8",
      },
      {
        title: "Indigo 500",
        value: "#6366f1",
        textColor: "#ffffff",
        bgColor: "#6366f1",
      },
      {
        title: "Indigo 600",
        value: "#4f46e5",
        textColor: "#ffffff",
        bgColor: "#4f46e5",
      },
      {
        title: "Indigo 700",
        value: "#4338ca",
        textColor: "#ffffff",
        bgColor: "#4338ca",
      },
      {
        title: "Indigo 800",
        value: "#3730a3",
        textColor: "#ffffff",
        bgColor: "#3730a3",
      },
      {
        title: "Indigo 900",
        value: "#312e81",
        textColor: "#ffffff",
        bgColor: "#312e81",
      },
      {
        title: "Indigo 950",
        value: "#1e1b4b",
        textColor: "#ffffff",
        bgColor: "#1e1b4b",
      },
      {
        title: "Violet 50",
        value: "#f5f3ff",
        textColor: "#000000",
        bgColor: "#f5f3ff",
      },
      {
        title: "Violet 100",
        value: "#ede9fe",
        textColor: "#000000",
        bgColor: "#ede9fe",
      },
      {
        title: "Violet 200",
        value: "#ddd6fe",
        textColor: "#000000",
        bgColor: "#ddd6fe",
      },
      {
        title: "Violet 300",
        value: "#c4b5fd",
        textColor: "#000000",
        bgColor: "#c4b5fd",
      },
      {
        title: "Violet 400",
        value: "#a78bfa",
        textColor: "#000000",
        bgColor: "#a78bfa",
      },
      {
        title: "Violet 500",
        value: "#8b5cf6",
        textColor: "#ffffff",
        bgColor: "#8b5cf6",
      },
      {
        title: "Violet 600",
        value: "#7c3aed",
        textColor: "#ffffff",
        bgColor: "#7c3aed",
      },
      {
        title: "Violet 700",
        value: "#6d28d9",
        textColor: "#ffffff",
        bgColor: "#6d28d9",
      },
      {
        title: "Violet 800",
        value: "#5b21b6",
        textColor: "#ffffff",
        bgColor: "#5b21b6",
      },
      {
        title: "Violet 900",
        value: "#4c1d95",
        textColor: "#ffffff",
        bgColor: "#4c1d95",
      },
      {
        title: "Violet 950",
        value: "#2e1065",
        textColor: "#ffffff",
        bgColor: "#2e1065",
      },
      {
        title: "Purple 50",
        value: "#faf5ff",
        textColor: "#000000",
        bgColor: "#faf5ff",
      },
      {
        title: "Purple 100",
        value: "#f3e8ff",
        textColor: "#000000",
        bgColor: "#f3e8ff",
      },
      {
        title: "Purple 200",
        value: "#e9d5ff",
        textColor: "#000000",
        bgColor: "#e9d5ff",
      },
      {
        title: "Purple 300",
        value: "#d8b4fe",
        textColor: "#000000",
        bgColor: "#d8b4fe",
      },
      {
        title: "Purple 400",
        value: "#c084fc",
        textColor: "#000000",
        bgColor: "#c084fc",
      },
      {
        title: "Purple 500",
        value: "#a855f7",
        textColor: "#ffffff",
        bgColor: "#a855f7",
      },
      {
        title: "Purple 600",
        value: "#9333ea",
        textColor: "#ffffff",
        bgColor: "#9333ea",
      },
      {
        title: "Purple 700",
        value: "#7e22ce",
        textColor: "#ffffff",
        bgColor: "#7e22ce",
      },
      {
        title: "Purple 800",
        value: "#6b21a8",
        textColor: "#ffffff",
        bgColor: "#6b21a8",
      },
      {
        title: "Purple 900",
        value: "#581c87",
        textColor: "#ffffff",
        bgColor: "#581c87",
      },
      {
        title: "Purple 950",
        value: "#3b0764",
        textColor: "#ffffff",
        bgColor: "#3b0764",
      },
      {
        title: "Fuchsia 50",
        value: "#fdf4ff",
        textColor: "#000000",
        bgColor: "#fdf4ff",
      },
      {
        title: "Fuchsia 100",
        value: "#fae8ff",
        textColor: "#000000",
        bgColor: "#fae8ff",
      },
      {
        title: "Fuchsia 200",
        value: "#f5d0fe",
        textColor: "#000000",
        bgColor: "#f5d0fe",
      },
      {
        title: "Fuchsia 300",
        value: "#f0abfc",
        textColor: "#000000",
        bgColor: "#f0abfc",
      },
      {
        title: "Fuchsia 400",
        value: "#e879f9",
        textColor: "#000000",
        bgColor: "#e879f9",
      },
      {
        title: "Fuchsia 500",
        value: "#d946ef",
        textColor: "#ffffff",
        bgColor: "#d946ef",
      },
      {
        title: "Fuchsia 600",
        value: "#c026d3",
        textColor: "#ffffff",
        bgColor: "#c026d3",
      },
      {
        title: "Fuchsia 700",
        value: "#a21caf",
        textColor: "#ffffff",
        bgColor: "#a21caf",
      },
      {
        title: "Fuchsia 800",
        value: "#86198f",
        textColor: "#ffffff",
        bgColor: "#86198f",
      },
      {
        title: "Fuchsia 900",
        value: "#701a75",
        textColor: "#ffffff",
        bgColor: "#701a75",
      },
      {
        title: "Fuchsia 950",
        value: "#4a044e",
        textColor: "#ffffff",
        bgColor: "#4a044e",
      },
      {
        title: "Pink 50",
        value: "#fdf2f8",
        textColor: "#000000",
        bgColor: "#fdf2f8",
      },
      {
        title: "Pink 100",
        value: "#fce7f3",
        textColor: "#000000",
        bgColor: "#fce7f3",
      },
      {
        title: "Pink 200",
        value: "#fbcfe8",
        textColor: "#000000",
        bgColor: "#fbcfe8",
      },
      {
        title: "Pink 300",
        value: "#f9a8d4",
        textColor: "#000000",
        bgColor: "#f9a8d4",
      },
      {
        title: "Pink 400",
        value: "#f472b6",
        textColor: "#000000",
        bgColor: "#f472b6",
      },
      {
        title: "Pink 500",
        value: "#ec4899",
        textColor: "#ffffff",
        bgColor: "#ec4899",
      },
      {
        title: "Pink 600",
        value: "#db2777",
        textColor: "#ffffff",
        bgColor: "#db2777",
      },
      {
        title: "Pink 700",
        value: "#be185d",
        textColor: "#ffffff",
        bgColor: "#be185d",
      },
      {
        title: "Pink 800",
        value: "#9d174d",
        textColor: "#ffffff",
        bgColor: "#9d174d",
      },
      {
        title: "Pink 900",
        value: "#831843",
        textColor: "#ffffff",
        bgColor: "#831843",
      },
      {
        title: "Pink 950",
        value: "#500724",
        textColor: "#ffffff",
        bgColor: "#500724",
      },
      {
        title: "Rose 50",
        value: "#fff1f2",
        textColor: "#000000",
        bgColor: "#fff1f2",
      },
      {
        title: "Rose 100",
        value: "#ffe4e6",
        textColor: "#000000",
        bgColor: "#ffe4e6",
      },
      {
        title: "Rose 200",
        value: "#fecdd3",
        textColor: "#000000",
        bgColor: "#fecdd3",
      },
      {
        title: "Rose 300",
        value: "#fda4af",
        textColor: "#000000",
        bgColor: "#fda4af",
      },
      {
        title: "Rose 400",
        value: "#fb7185",
        textColor: "#000000",
        bgColor: "#fb7185",
      },
      {
        title: "Rose 500",
        value: "#f43f5e",
        textColor: "#ffffff",
        bgColor: "#f43f5e",
      },
      {
        title: "Rose 600",
        value: "#e11d48",
        textColor: "#ffffff",
        bgColor: "#e11d48",
      },
      {
        title: "Rose 700",
        value: "#be123c",
        textColor: "#ffffff",
        bgColor: "#be123c",
      },
      {
        title: "Rose 800",
        value: "#9f1239",
        textColor: "#ffffff",
        bgColor: "#9f1239",
      },
      {
        title: "Rose 900",
        value: "#881337",
        textColor: "#ffffff",
        bgColor: "#881337",
      },
      {
        title: "Rose 950",
        value: "#4c0519",
        textColor: "#ffffff",
        bgColor: "#4c0519",
      },
      {
        title: "Slate 50",
        value: "#f8fafc",
        textColor: "#000000",
        bgColor: "#f8fafc",
      },
      {
        title: "Slate 100",
        value: "#f1f5f9",
        textColor: "#000000",
        bgColor: "#f1f5f9",
      },
      {
        title: "Slate 200",
        value: "#e2e8f0",
        textColor: "#000000",
        bgColor: "#e2e8f0",
      },
      {
        title: "Slate 300",
        value: "#cbd5e1",
        textColor: "#000000",
        bgColor: "#cbd5e1",
      },
      {
        title: "Slate 400",
        value: "#94a3b8",
        textColor: "#000000",
        bgColor: "#94a3b8",
      },
      {
        title: "Slate 500",
        value: "#64748b",
        textColor: "#ffffff",
        bgColor: "#64748b",
      },
      {
        title: "Slate 600",
        value: "#475569",
        textColor: "#ffffff",
        bgColor: "#475569",
      },
      {
        title: "Slate 700",
        value: "#334155",
        textColor: "#ffffff",
        bgColor: "#334155",
      },
      {
        title: "Slate 800",
        value: "#1e293b",
        textColor: "#ffffff",
        bgColor: "#1e293b",
      },
      {
        title: "Slate 900",
        value: "#0f172a",
        textColor: "#ffffff",
        bgColor: "#0f172a",
      },
      {
        title: "Slate 950",
        value: "#020617",
        textColor: "#ffffff",
        bgColor: "#020617",
      },
      {
        title: "Gray 50",
        value: "#f9fafb",
        textColor: "#000000",
        bgColor: "#f9fafb",
      },
      {
        title: "Gray 100",
        value: "#f3f4f6",
        textColor: "#000000",
        bgColor: "#f3f4f6",
      },
      {
        title: "Gray 200",
        value: "#e5e7eb",
        textColor: "#000000",
        bgColor: "#e5e7eb",
      },
      {
        title: "Gray 300",
        value: "#d1d5db",
        textColor: "#000000",
        bgColor: "#d1d5db",
      },
      {
        title: "Gray 400",
        value: "#9ca3af",
        textColor: "#000000",
        bgColor: "#9ca3af",
      },
      {
        title: "Gray 500",
        value: "#6b7280",
        textColor: "#ffffff",
        bgColor: "#6b7280",
      },
      {
        title: "Gray 600",
        value: "#4b5563",
        textColor: "#ffffff",
        bgColor: "#4b5563",
      },
      {
        title: "Gray 700",
        value: "#374151",
        textColor: "#ffffff",
        bgColor: "#374151",
      },
      {
        title: "Gray 800",
        value: "#1f2937",
        textColor: "#ffffff",
        bgColor: "#1f2937",
      },
      {
        title: "Gray 900",
        value: "#111827",
        textColor: "#ffffff",
        bgColor: "#111827",
      },
      {
        title: "Gray 950",
        value: "#030712",
        textColor: "#ffffff",
        bgColor: "#030712",
      },
      {
        title: "Zinc 50",
        value: "#fafafa",
        textColor: "#000000",
        bgColor: "#fafafa",
      },
      {
        title: "Zinc 100",
        value: "#f4f4f5",
        textColor: "#000000",
        bgColor: "#f4f4f5",
      },
      {
        title: "Zinc 200",
        value: "#e4e4e7",
        textColor: "#000000",
        bgColor: "#e4e4e7",
      },
      {
        title: "Zinc 300",
        value: "#d4d4d8",
        textColor: "#000000",
        bgColor: "#d4d4d8",
      },
      {
        title: "Zinc 400",
        value: "#a1a1aa",
        textColor: "#000000",
        bgColor: "#a1a1aa",
      },
      {
        title: "Zinc 500",
        value: "#71717a",
        textColor: "#ffffff",
        bgColor: "#71717a",
      },
      {
        title: "Zinc 600",
        value: "#52525b",
        textColor: "#ffffff",
        bgColor: "#52525b",
      },
      {
        title: "Zinc 700",
        value: "#3f3f46",
        textColor: "#ffffff",
        bgColor: "#3f3f46",
      },
      {
        title: "Zinc 800",
        value: "#27272a",
        textColor: "#ffffff",
        bgColor: "#27272a",
      },
      {
        title: "Zinc 900",
        value: "#18181b",
        textColor: "#ffffff",
        bgColor: "#18181b",
      },
      {
        title: "Zinc 950",
        value: "#09090b",
        textColor: "#ffffff",
        bgColor: "#09090b",
      },
      {
        title: "Neutral 50",
        value: "#fafafa",
        textColor: "#000000",
        bgColor: "#fafafa",
      },
      {
        title: "Neutral 100",
        value: "#f5f5f5",
        textColor: "#000000",
        bgColor: "#f5f5f5",
      },
      {
        title: "Neutral 200",
        value: "#e5e5e5",
        textColor: "#000000",
        bgColor: "#e5e5e5",
      },
      {
        title: "Neutral 300",
        value: "#d4d4d4",
        textColor: "#000000",
        bgColor: "#d4d4d4",
      },
      {
        title: "Neutral 400",
        value: "#a3a3a3",
        textColor: "#000000",
        bgColor: "#a3a3a3",
      },
      {
        title: "Neutral 500",
        value: "#737373",
        textColor: "#ffffff",
        bgColor: "#737373",
      },
      {
        title: "Neutral 600",
        value: "#525252",
        textColor: "#ffffff",
        bgColor: "#525252",
      },
      {
        title: "Neutral 700",
        value: "#404040",
        textColor: "#ffffff",
        bgColor: "#404040",
      },
      {
        title: "Neutral 800",
        value: "#262626",
        textColor: "#ffffff",
        bgColor: "#262626",
      },
      {
        title: "Neutral 900",
        value: "#171717",
        textColor: "#ffffff",
        bgColor: "#171717",
      },
      {
        title: "Neutral 950",
        value: "#0a0a0a",
        textColor: "#ffffff",
        bgColor: "#0a0a0a",
      },
      {
        title: "Stone 50",
        value: "#fafaf9",
        textColor: "#000000",
        bgColor: "#fafaf9",
      },
      {
        title: "Stone 100",
        value: "#f5f5f4",
        textColor: "#000000",
        bgColor: "#f5f5f4",
      },
      {
        title: "Stone 200",
        value: "#e7e5e4",
        textColor: "#000000",
        bgColor: "#e7e5e4",
      },
      {
        title: "Stone 300",
        value: "#d6d3d1",
        textColor: "#000000",
        bgColor: "#d6d3d1",
      },
      {
        title: "Stone 400",
        value: "#a8a29e",
        textColor: "#000000",
        bgColor: "#a8a29e",
      },
      {
        title: "Stone 500",
        value: "#78716c",
        textColor: "#ffffff",
        bgColor: "#78716c",
      },
      {
        title: "Stone 600",
        value: "#57534e",
        textColor: "#ffffff",
        bgColor: "#57534e",
      },
      {
        title: "Stone 700",
        value: "#44403c",
        textColor: "#ffffff",
        bgColor: "#44403c",
      },
      {
        title: "Stone 800",
        value: "#292524",
        textColor: "#ffffff",
        bgColor: "#292524",
      },
      {
        title: "Stone 900",
        value: "#1c1917",
        textColor: "#ffffff",
        bgColor: "#1c1917",
      },
      {
        title: "Stone 950",
        value: "#0c0a09",
        textColor: "#ffffff",
        bgColor: "#0c0a09",
      },
    ],
  },
  {
    groupTitle: "Material Colors",
    colors: [
      {
        title: "Gray 50",
        value: "#fafafa",
        textColor: "#000000",
        bgColor: "#fafafa",
      },
      {
        title: "Gray 100",
        value: "#f5f5f5",
        textColor: "#000000",
        bgColor: "#f5f5f5",
      },
      {
        title: "Gray 200",
        value: "#eeeeee",
        textColor: "#000000",
        bgColor: "#eeeeee",
      },
      {
        title: "Gray 300",
        value: "#e0e0e0",
        textColor: "#000000",
        bgColor: "#e0e0e0",
      },
      {
        title: "Gray 400",
        value: "#bdbdbd",
        textColor: "#000000",
        bgColor: "#bdbdbd",
      },
      {
        title: "Gray 500",
        value: "#9e9e9e",
        textColor: "#000000",
        bgColor: "#9e9e9e",
      },
      {
        title: "Gray 600",
        value: "#757575",
        textColor: "#ffffff",
        bgColor: "#757575",
      },
      {
        title: "Gray 700",
        value: "#616161",
        textColor: "#ffffff",
        bgColor: "#616161",
      },
      {
        title: "Gray 800",
        value: "#424242",
        textColor: "#ffffff",
        bgColor: "#424242",
      },
      {
        title: "Gray 900",
        value: "#212121",
        textColor: "#ffffff",
        bgColor: "#212121",
      },
      {
        title: "Red 50",
        value: "#ffebee",
        textColor: "#000000",
        bgColor: "#ffebee",
      },
      {
        title: "Red 100",
        value: "#ffcdd2",
        textColor: "#000000",
        bgColor: "#ffcdd2",
      },
      {
        title: "Red 200",
        value: "#ef9a9a",
        textColor: "#000000",
        bgColor: "#ef9a9a",
      },
      {
        title: "Red 300",
        value: "#e57373",
        textColor: "#000000",
        bgColor: "#e57373",
      },
      {
        title: "Red 400",
        value: "#ef5350",
        textColor: "#000000",
        bgColor: "#ef5350",
      },
      {
        title: "Red 500",
        value: "#f44336",
        textColor: "#ffffff",
        bgColor: "#f44336",
      },
      {
        title: "Red 600",
        value: "#e53935",
        textColor: "#ffffff",
        bgColor: "#e53935",
      },
      {
        title: "Red 700",
        value: "#d32f2f",
        textColor: "#ffffff",
        bgColor: "#d32f2f",
      },
      {
        title: "Red 800",
        value: "#c62828",
        textColor: "#ffffff",
        bgColor: "#c62828",
      },
      {
        title: "Red 900",
        value: "#b71c1c",
        textColor: "#ffffff",
        bgColor: "#b71c1c",
      },
      {
        title: "Red a100",
        value: "#ff8a80",
        textColor: "#000000",
        bgColor: "#ff8a80",
      },
      {
        title: "Red a200",
        value: "#ff5252",
        textColor: "#000000",
        bgColor: "#ff5252",
      },
      {
        title: "Red a400",
        value: "#ff1744",
        textColor: "#ffffff",
        bgColor: "#ff1744",
      },
      {
        title: "Red a700",
        value: "#d50000",
        textColor: "#ffffff",
        bgColor: "#d50000",
      },
      {
        title: "Pink 50",
        value: "#fce4ec",
        textColor: "#000000",
        bgColor: "#fce4ec",
      },
      {
        title: "Pink 100",
        value: "#f8bbd0",
        textColor: "#000000",
        bgColor: "#f8bbd0",
      },
      {
        title: "Pink 200",
        value: "#f48fb1",
        textColor: "#000000",
        bgColor: "#f48fb1",
      },
      {
        title: "Pink 300",
        value: "#f06292",
        textColor: "#000000",
        bgColor: "#f06292",
      },
      {
        title: "Pink 400",
        value: "#ec407a",
        textColor: "#000000",
        bgColor: "#ec407a",
      },
      {
        title: "Pink 500",
        value: "#e91e63",
        textColor: "#ffffff",
        bgColor: "#e91e63",
      },
      {
        title: "Pink 600",
        value: "#d81b60",
        textColor: "#ffffff",
        bgColor: "#d81b60",
      },
      {
        title: "Pink 700",
        value: "#c2185b",
        textColor: "#ffffff",
        bgColor: "#c2185b",
      },
      {
        title: "Pink 800",
        value: "#ad1457",
        textColor: "#ffffff",
        bgColor: "#ad1457",
      },
      {
        title: "Pink 900",
        value: "#880e4f",
        textColor: "#ffffff",
        bgColor: "#880e4f",
      },
      {
        title: "Pink a100",
        value: "#ff80ab",
        textColor: "#000000",
        bgColor: "#ff80ab",
      },
      {
        title: "Pink a200",
        value: "#ff4081",
        textColor: "#000000",
        bgColor: "#ff4081",
      },
      {
        title: "Pink a400",
        value: "#f50057",
        textColor: "#ffffff",
        bgColor: "#f50057",
      },
      {
        title: "Pink a700",
        value: "#c51162",
        textColor: "#ffffff",
        bgColor: "#c51162",
      },
      {
        title: "Purple 50",
        value: "#f3e5f5",
        textColor: "#000000",
        bgColor: "#f3e5f5",
      },
      {
        title: "Purple 100",
        value: "#e1bee7",
        textColor: "#000000",
        bgColor: "#e1bee7",
      },
      {
        title: "Purple 200",
        value: "#ce93d8",
        textColor: "#000000",
        bgColor: "#ce93d8",
      },
      {
        title: "Purple 300",
        value: "#ba68c8",
        textColor: "#000000",
        bgColor: "#ba68c8",
      },
      {
        title: "Purple 400",
        value: "#ab47bc",
        textColor: "#000000",
        bgColor: "#ab47bc",
      },
      {
        title: "Purple 500",
        value: "#9c27b0",
        textColor: "#ffffff",
        bgColor: "#9c27b0",
      },
      {
        title: "Purple 600",
        value: "#8e24aa",
        textColor: "#ffffff",
        bgColor: "#8e24aa",
      },
      {
        title: "Purple 700",
        value: "#7b1fa2",
        textColor: "#ffffff",
        bgColor: "#7b1fa2",
      },
      {
        title: "Purple 800",
        value: "#6a1b9a",
        textColor: "#ffffff",
        bgColor: "#6a1b9a",
      },
      {
        title: "Purple 900",
        value: "#4a148c",
        textColor: "#ffffff",
        bgColor: "#4a148c",
      },
      {
        title: "Purple a100",
        value: "#ea80fc",
        textColor: "#000000",
        bgColor: "#ea80fc",
      },
      {
        title: "Purple a200",
        value: "#e040fb",
        textColor: "#000000",
        bgColor: "#e040fb",
      },
      {
        title: "Purple a400",
        value: "#d500f9",
        textColor: "#000000",
        bgColor: "#d500f9",
      },
      {
        title: "Purple a700",
        value: "#aa00ff",
        textColor: "#ffffff",
        bgColor: "#aa00ff",
      },
      {
        title: "Deep Purple 50",
        value: "#ede7f6",
        textColor: "#000000",
        bgColor: "#ede7f6",
      },
      {
        title: "Deep Purple 100",
        value: "#d1c4e9",
        textColor: "#000000",
        bgColor: "#d1c4e9",
      },
      {
        title: "Deep Purple 200",
        value: "#b39ddb",
        textColor: "#000000",
        bgColor: "#b39ddb",
      },
      {
        title: "Deep Purple 300",
        value: "#9575cd",
        textColor: "#000000",
        bgColor: "#9575cd",
      },
      {
        title: "Deep Purple 400",
        value: "#7e57c2",
        textColor: "#000000",
        bgColor: "#7e57c2",
      },
      {
        title: "Deep Purple 500",
        value: "#673ab7",
        textColor: "#ffffff",
        bgColor: "#673ab7",
      },
      {
        title: "Deep Purple 600",
        value: "#5e35b1",
        textColor: "#ffffff",
        bgColor: "#5e35b1",
      },
      {
        title: "Deep Purple 700",
        value: "#512da8",
        textColor: "#ffffff",
        bgColor: "#512da8",
      },
      {
        title: "Deep Purple 800",
        value: "#4527a0",
        textColor: "#ffffff",
        bgColor: "#4527a0",
      },
      {
        title: "Deep Purple 900",
        value: "#311b92",
        textColor: "#ffffff",
        bgColor: "#311b92",
      },
      {
        title: "Deep Purple a100",
        value: "#b388ff",
        textColor: "#000000",
        bgColor: "#b388ff",
      },
      {
        title: "Deep Purple a200",
        value: "#7c4dff",
        textColor: "#000000",
        bgColor: "#7c4dff",
      },
      {
        title: "Deep Purple a400",
        value: "#651fff",
        textColor: "#ffffff",
        bgColor: "#651fff",
      },
      {
        title: "Deep Purple a700",
        value: "#6200ea",
        textColor: "#ffffff",
        bgColor: "#6200ea",
      },
      {
        title: "Indigo 50",
        value: "#e8eaf6",
        textColor: "#000000",
        bgColor: "#e8eaf6",
      },
      {
        title: "Indigo 100",
        value: "#c5cae9",
        textColor: "#000000",
        bgColor: "#c5cae9",
      },
      {
        title: "Indigo 200",
        value: "#9fa8da",
        textColor: "#000000",
        bgColor: "#9fa8da",
      },
      {
        title: "Indigo 300",
        value: "#7986cb",
        textColor: "#000000",
        bgColor: "#7986cb",
      },
      {
        title: "Indigo 400",
        value: "#5c6bc0",
        textColor: "#000000",
        bgColor: "#5c6bc0",
      },
      {
        title: "Indigo 500",
        value: "#3f51b5",
        textColor: "#ffffff",
        bgColor: "#3f51b5",
      },
      {
        title: "Indigo 600",
        value: "#3949ab",
        textColor: "#ffffff",
        bgColor: "#3949ab",
      },
      {
        title: "Indigo 700",
        value: "#303f9f",
        textColor: "#ffffff",
        bgColor: "#303f9f",
      },
      {
        title: "Indigo 800",
        value: "#283593",
        textColor: "#ffffff",
        bgColor: "#283593",
      },
      {
        title: "Indigo 900",
        value: "#1a237e",
        textColor: "#ffffff",
        bgColor: "#1a237e",
      },
      {
        title: "Indigo a100",
        value: "#8c9eff",
        textColor: "#000000",
        bgColor: "#8c9eff",
      },
      {
        title: "Indigo a200",
        value: "#536dfe",
        textColor: "#000000",
        bgColor: "#536dfe",
      },
      {
        title: "Indigo a400",
        value: "#3d5afe",
        textColor: "#ffffff",
        bgColor: "#3d5afe",
      },
      {
        title: "Indigo a700",
        value: "#304ffe",
        textColor: "#ffffff",
        bgColor: "#304ffe",
      },
      {
        title: "Blue 50",
        value: "#e3f2fd",
        textColor: "#000000",
        bgColor: "#e3f2fd",
      },
      {
        title: "Blue 100",
        value: "#bbdefb",
        textColor: "#000000",
        bgColor: "#bbdefb",
      },
      {
        title: "Blue 200",
        value: "#90caf9",
        textColor: "#000000",
        bgColor: "#90caf9",
      },
      {
        title: "Blue 300",
        value: "#64b5f6",
        textColor: "#000000",
        bgColor: "#64b5f6",
      },
      {
        title: "Blue 400",
        value: "#42a5f5",
        textColor: "#000000",
        bgColor: "#42a5f5",
      },
      {
        title: "Blue 500",
        value: "#2196f3",
        textColor: "#ffffff",
        bgColor: "#2196f3",
      },
      {
        title: "Blue 600",
        value: "#1e88e5",
        textColor: "#ffffff",
        bgColor: "#1e88e5",
      },
      {
        title: "Blue 700",
        value: "#1976d2",
        textColor: "#ffffff",
        bgColor: "#1976d2",
      },
      {
        title: "Blue 800",
        value: "#1565c0",
        textColor: "#ffffff",
        bgColor: "#1565c0",
      },
      {
        title: "Blue 900",
        value: "#0d47a1",
        textColor: "#ffffff",
        bgColor: "#0d47a1",
      },
      {
        title: "Blue a100",
        value: "#82b1ff",
        textColor: "#000000",
        bgColor: "#82b1ff",
      },
      {
        title: "Blue a200",
        value: "#448aff",
        textColor: "#000000",
        bgColor: "#448aff",
      },
      {
        title: "Blue a400",
        value: "#2979ff",
        textColor: "#ffffff",
        bgColor: "#2979ff",
      },
      {
        title: "Blue a700",
        value: "#2962ff",
        textColor: "#ffffff",
        bgColor: "#2962ff",
      },
      {
        title: "Light Blue 50",
        value: "#e1f5fe",
        textColor: "#000000",
        bgColor: "#e1f5fe",
      },
      {
        title: "Light Blue 100",
        value: "#b3e5fc",
        textColor: "#000000",
        bgColor: "#b3e5fc",
      },
      {
        title: "Light Blue 200",
        value: "#81d4fa",
        textColor: "#000000",
        bgColor: "#81d4fa",
      },
      {
        title: "Light Blue 300",
        value: "#4fc3f7",
        textColor: "#000000",
        bgColor: "#4fc3f7",
      },
      {
        title: "Light Blue 400",
        value: "#29b6f6",
        textColor: "#000000",
        bgColor: "#29b6f6",
      },
      {
        title: "Light Blue 500",
        value: "#03a9f4",
        textColor: "#ffffff",
        bgColor: "#03a9f4",
      },
      {
        title: "Light Blue 600",
        value: "#039be5",
        textColor: "#ffffff",
        bgColor: "#039be5",
      },
      {
        title: "Light Blue 700",
        value: "#0288d1",
        textColor: "#ffffff",
        bgColor: "#0288d1",
      },
      {
        title: "Light Blue 800",
        value: "#0277bd",
        textColor: "#ffffff",
        bgColor: "#0277bd",
      },
      {
        title: "Light Blue 900",
        value: "#01579b",
        textColor: "#ffffff",
        bgColor: "#01579b",
      },
      {
        title: "Light Blue a100",
        value: "#80d8ff",
        textColor: "#000000",
        bgColor: "#80d8ff",
      },
      {
        title: "Light Blue a200",
        value: "#40c4ff",
        textColor: "#000000",
        bgColor: "#40c4ff",
      },
      {
        title: "Light Blue a400",
        value: "#00b0ff",
        textColor: "#000000",
        bgColor: "#00b0ff",
      },
      {
        title: "Light Blue a700",
        value: "#0091ea",
        textColor: "#ffffff",
        bgColor: "#0091ea",
      },
      {
        title: "Cyan 50",
        value: "#e0f7fa",
        textColor: "#000000",
        bgColor: "#e0f7fa",
      },
      {
        title: "Cyan 100",
        value: "#b2ebf2",
        textColor: "#000000",
        bgColor: "#b2ebf2",
      },
      {
        title: "Cyan 200",
        value: "#80deea",
        textColor: "#000000",
        bgColor: "#80deea",
      },
      {
        title: "Cyan 300",
        value: "#4dd0e1",
        textColor: "#000000",
        bgColor: "#4dd0e1",
      },
      {
        title: "Cyan 400",
        value: "#26c6da",
        textColor: "#000000",
        bgColor: "#26c6da",
      },
      {
        title: "Cyan 500",
        value: "#00bcd4",
        textColor: "#ffffff",
        bgColor: "#00bcd4",
      },
      {
        title: "Cyan 600",
        value: "#00acc1",
        textColor: "#ffffff",
        bgColor: "#00acc1",
      },
      {
        title: "Cyan 700",
        value: "#0097a7",
        textColor: "#ffffff",
        bgColor: "#0097a7",
      },
      {
        title: "Cyan 800",
        value: "#00838f",
        textColor: "#ffffff",
        bgColor: "#00838f",
      },
      {
        title: "Cyan 900",
        value: "#006064",
        textColor: "#ffffff",
        bgColor: "#006064",
      },
      {
        title: "Cyan a100",
        value: "#84ffff",
        textColor: "#000000",
        bgColor: "#84ffff",
      },
      {
        title: "Cyan a200",
        value: "#18ffff",
        textColor: "#000000",
        bgColor: "#18ffff",
      },
      {
        title: "Cyan a400",
        value: "#00e5ff",
        textColor: "#000000",
        bgColor: "#00e5ff",
      },
      {
        title: "Cyan a700",
        value: "#00b8d4",
        textColor: "#ffffff",
        bgColor: "#00b8d4",
      },
      {
        title: "Teal 50",
        value: "#e0f2f1",
        textColor: "#000000",
        bgColor: "#e0f2f1",
      },
      {
        title: "Teal 100",
        value: "#b2dfdb",
        textColor: "#000000",
        bgColor: "#b2dfdb",
      },
      {
        title: "Teal 200",
        value: "#80cbc4",
        textColor: "#000000",
        bgColor: "#80cbc4",
      },
      {
        title: "Teal 300",
        value: "#4db6ac",
        textColor: "#000000",
        bgColor: "#4db6ac",
      },
      {
        title: "Teal 400",
        value: "#26a69a",
        textColor: "#000000",
        bgColor: "#26a69a",
      },
      {
        title: "Teal 500",
        value: "#009688",
        textColor: "#ffffff",
        bgColor: "#009688",
      },
      {
        title: "Teal 600",
        value: "#00897b",
        textColor: "#ffffff",
        bgColor: "#00897b",
      },
      {
        title: "Teal 700",
        value: "#00796b",
        textColor: "#ffffff",
        bgColor: "#00796b",
      },
      {
        title: "Teal 800",
        value: "#00695c",
        textColor: "#ffffff",
        bgColor: "#00695c",
      },
      {
        title: "Teal 900",
        value: "#004d40",
        textColor: "#ffffff",
        bgColor: "#004d40",
      },
      {
        title: "Teal a100",
        value: "#a7ffeb",
        textColor: "#000000",
        bgColor: "#a7ffeb",
      },
      {
        title: "Teal a200",
        value: "#64ffda",
        textColor: "#000000",
        bgColor: "#64ffda",
      },
      {
        title: "Teal a400",
        value: "#1de9b6",
        textColor: "#000000",
        bgColor: "#1de9b6",
      },
      {
        title: "Teal a700",
        value: "#00bfa5",
        textColor: "#ffffff",
        bgColor: "#00bfa5",
      },
      {
        title: "Green 50",
        value: "#e8f5e9",
        textColor: "#000000",
        bgColor: "#e8f5e9",
      },
      {
        title: "Green 100",
        value: "#c8e6c9",
        textColor: "#000000",
        bgColor: "#c8e6c9",
      },
      {
        title: "Green 200",
        value: "#a5d6a7",
        textColor: "#000000",
        bgColor: "#a5d6a7",
      },
      {
        title: "Green 300",
        value: "#81c784",
        textColor: "#000000",
        bgColor: "#81c784",
      },
      {
        title: "Green 400",
        value: "#66bb6a",
        textColor: "#000000",
        bgColor: "#66bb6a",
      },
      {
        title: "Green 500",
        value: "#4caf50",
        textColor: "#ffffff",
        bgColor: "#4caf50",
      },
      {
        title: "Green 600",
        value: "#43a047",
        textColor: "#ffffff",
        bgColor: "#43a047",
      },
      {
        title: "Green 700",
        value: "#388e3c",
        textColor: "#ffffff",
        bgColor: "#388e3c",
      },
      {
        title: "Green 800",
        value: "#2e7d32",
        textColor: "#ffffff",
        bgColor: "#2e7d32",
      },
      {
        title: "Green 900",
        value: "#1b5e20",
        textColor: "#ffffff",
        bgColor: "#1b5e20",
      },
      {
        title: "Green a100",
        value: "#b9f6ca",
        textColor: "#000000",
        bgColor: "#b9f6ca",
      },
      {
        title: "Green a200",
        value: "#69f0ae",
        textColor: "#000000",
        bgColor: "#69f0ae",
      },
      {
        title: "Green a400",
        value: "#00e676",
        textColor: "#000000",
        bgColor: "#00e676",
      },
      {
        title: "Green a700",
        value: "#00c853",
        textColor: "#ffffff",
        bgColor: "#00c853",
      },
      {
        title: "Light Green 50",
        value: "#f1f8e9",
        textColor: "#000000",
        bgColor: "#f1f8e9",
      },
      {
        title: "Light Green 100",
        value: "#dcedc8",
        textColor: "#000000",
        bgColor: "#dcedc8",
      },
      {
        title: "Light Green 200",
        value: "#c5e1a5",
        textColor: "#000000",
        bgColor: "#c5e1a5",
      },
      {
        title: "Light Green 300",
        value: "#aed581",
        textColor: "#000000",
        bgColor: "#aed581",
      },
      {
        title: "Light Green 400",
        value: "#9ccc65",
        textColor: "#000000",
        bgColor: "#9ccc65",
      },
      {
        title: "Light Green 500",
        value: "#8bc34a",
        textColor: "#ffffff",
        bgColor: "#8bc34a",
      },
      {
        title: "Light Green 600",
        value: "#7cb342",
        textColor: "#ffffff",
        bgColor: "#7cb342",
      },
      {
        title: "Light Green 700",
        value: "#689f38",
        textColor: "#ffffff",
        bgColor: "#689f38",
      },
      {
        title: "Light Green 800",
        value: "#558b2f",
        textColor: "#ffffff",
        bgColor: "#558b2f",
      },
      {
        title: "Light Green 900",
        value: "#33691e",
        textColor: "#ffffff",
        bgColor: "#33691e",
      },
      {
        title: "Light Green a100",
        value: "#ccff90",
        textColor: "#000000",
        bgColor: "#ccff90",
      },
      {
        title: "Light Green a200",
        value: "#b2ff59",
        textColor: "#000000",
        bgColor: "#b2ff59",
      },
      {
        title: "Light Green a400",
        value: "#76ff03",
        textColor: "#000000",
        bgColor: "#76ff03",
      },
      {
        title: "Light Green a700",
        value: "#64dd17",
        textColor: "#ffffff",
        bgColor: "#64dd17",
      },
      {
        title: "Lime 50",
        value: "#f9fbe7",
        textColor: "#000000",
        bgColor: "#f9fbe7",
      },
      {
        title: "Lime 100",
        value: "#f0f4c3",
        textColor: "#000000",
        bgColor: "#f0f4c3",
      },
      {
        title: "Lime 200",
        value: "#e6ee9c",
        textColor: "#000000",
        bgColor: "#e6ee9c",
      },
      {
        title: "Lime 300",
        value: "#dce775",
        textColor: "#000000",
        bgColor: "#dce775",
      },
      {
        title: "Lime 400",
        value: "#d4e157",
        textColor: "#000000",
        bgColor: "#d4e157",
      },
      {
        title: "Lime 500",
        value: "#cddc39",
        textColor: "#000000",
        bgColor: "#cddc39",
      },
      {
        title: "Lime 600",
        value: "#c0ca33",
        textColor: "#ffffff",
        bgColor: "#c0ca33",
      },
      {
        title: "Lime 700",
        value: "#afb42b",
        textColor: "#ffffff",
        bgColor: "#afb42b",
      },
      {
        title: "Lime 800",
        value: "#9e9d24",
        textColor: "#ffffff",
        bgColor: "#9e9d24",
      },
      {
        title: "Lime 900",
        value: "#827717",
        textColor: "#ffffff",
        bgColor: "#827717",
      },
      {
        title: "Lime a100",
        value: "#f4ff81",
        textColor: "#000000",
        bgColor: "#f4ff81",
      },
      {
        title: "Lime a200",
        value: "#eeff41",
        textColor: "#000000",
        bgColor: "#eeff41",
      },
      {
        title: "Lime a400",
        value: "#c6ff00",
        textColor: "#000000",
        bgColor: "#c6ff00",
      },
      {
        title: "Lime a700",
        value: "#aeea00",
        textColor: "#ffffff",
        bgColor: "#aeea00",
      },
      {
        title: "Yellow 50",
        value: "#fffde7",
        textColor: "#000000",
        bgColor: "#fffde7",
      },
      {
        title: "Yellow 100",
        value: "#fff9c4",
        textColor: "#000000",
        bgColor: "#fff9c4",
      },
      {
        title: "Yellow 200",
        value: "#fff59d",
        textColor: "#000000",
        bgColor: "#fff59d",
      },
      {
        title: "Yellow 300",
        value: "#fff176",
        textColor: "#000000",
        bgColor: "#fff176",
      },
      {
        title: "Yellow 400",
        value: "#ffee58",
        textColor: "#000000",
        bgColor: "#ffee58",
      },
      {
        title: "Yellow 500",
        value: "#ffeb3b",
        textColor: "#000000",
        bgColor: "#ffeb3b",
      },
      {
        title: "Yellow 600",
        value: "#fdd835",
        textColor: "#000000",
        bgColor: "#fdd835",
      },
      {
        title: "Yellow 700",
        value: "#fbc02d",
        textColor: "#000000",
        bgColor: "#fbc02d",
      },
      {
        title: "Yellow 800",
        value: "#f9a825",
        textColor: "#ffffff",
        bgColor: "#f9a825",
      },
      {
        title: "Yellow 900",
        value: "#f57f17",
        textColor: "#ffffff",
        bgColor: "#f57f17",
      },
      {
        title: "Yellow a100",
        value: "#ffff8d",
        textColor: "#000000",
        bgColor: "#ffff8d",
      },
      {
        title: "Yellow a200",
        value: "#ffff00",
        textColor: "#000000",
        bgColor: "#ffff00",
      },
      {
        title: "Yellow a400",
        value: "#ffea00",
        textColor: "#000000",
        bgColor: "#ffea00",
      },
      {
        title: "Yellow a700",
        value: "#ffd600",
        textColor: "#ffffff",
        bgColor: "#ffd600",
      },
      {
        title: "Amber 50",
        value: "#fff8e1",
        textColor: "#000000",
        bgColor: "#fff8e1",
      },
      {
        title: "Amber 100",
        value: "#ffecb3",
        textColor: "#000000",
        bgColor: "#ffecb3",
      },
      {
        title: "Amber 200",
        value: "#ffe082",
        textColor: "#000000",
        bgColor: "#ffe082",
      },
      {
        title: "Amber 300",
        value: "#ffd54f",
        textColor: "#000000",
        bgColor: "#ffd54f",
      },
      {
        title: "Amber 400",
        value: "#ffca28",
        textColor: "#000000",
        bgColor: "#ffca28",
      },
      {
        title: "Amber 500",
        value: "#ffc107",
        textColor: "#000000",
        bgColor: "#ffc107",
      },
      {
        title: "Amber 600",
        value: "#ffb300",
        textColor: "#ffffff",
        bgColor: "#ffb300",
      },
      {
        title: "Amber 700",
        value: "#ffa000",
        textColor: "#ffffff",
        bgColor: "#ffa000",
      },
      {
        title: "Amber 800",
        value: "#ff8f00",
        textColor: "#ffffff",
        bgColor: "#ff8f00",
      },
      {
        title: "Amber 900",
        value: "#ff6f00",
        textColor: "#ffffff",
        bgColor: "#ff6f00",
      },
      {
        title: "Amber a100",
        value: "#ffe57f",
        textColor: "#000000",
        bgColor: "#ffe57f",
      },
      {
        title: "Amber a200",
        value: "#ffd740",
        textColor: "#000000",
        bgColor: "#ffd740",
      },
      {
        title: "Amber a400",
        value: "#ffc400",
        textColor: "#000000",
        bgColor: "#ffc400",
      },
      {
        title: "Amber a700",
        value: "#ffab00",
        textColor: "#ffffff",
        bgColor: "#ffab00",
      },
      {
        title: "Orange 50",
        value: "#fff3e0",
        textColor: "#000000",
        bgColor: "#fff3e0",
      },
      {
        title: "Orange 100",
        value: "#ffe0b2",
        textColor: "#000000",
        bgColor: "#ffe0b2",
      },
      {
        title: "Orange 200",
        value: "#ffcc80",
        textColor: "#000000",
        bgColor: "#ffcc80",
      },
      {
        title: "Orange 300",
        value: "#ffb74d",
        textColor: "#000000",
        bgColor: "#ffb74d",
      },
      {
        title: "Orange 400",
        value: "#ffa726",
        textColor: "#000000",
        bgColor: "#ffa726",
      },
      {
        title: "Orange 500",
        value: "#ff9800",
        textColor: "#ffffff",
        bgColor: "#ff9800",
      },
      {
        title: "Orange 600",
        value: "#fb8c00",
        textColor: "#ffffff",
        bgColor: "#fb8c00",
      },
      {
        title: "Orange 700",
        value: "#f57c00",
        textColor: "#ffffff",
        bgColor: "#f57c00",
      },
      {
        title: "Orange 800",
        value: "#ef6c00",
        textColor: "#ffffff",
        bgColor: "#ef6c00",
      },
      {
        title: "Orange 900",
        value: "#e65100",
        textColor: "#ffffff",
        bgColor: "#e65100",
      },
      {
        title: "Orange a100",
        value: "#ffd180",
        textColor: "#000000",
        bgColor: "#ffd180",
      },
      {
        title: "Orange a200",
        value: "#ffab40",
        textColor: "#000000",
        bgColor: "#ffab40",
      },
      {
        title: "Orange a400",
        value: "#ff9100",
        textColor: "#000000",
        bgColor: "#ff9100",
      },
      {
        title: "Orange a700",
        value: "#ff6d00",
        textColor: "#ffffff",
        bgColor: "#ff6d00",
      },
      {
        title: "Deep Orange 50",
        value: "#fbe9e7",
        textColor: "#000000",
        bgColor: "#fbe9e7",
      },
      {
        title: "Deep Orange 100",
        value: "#ffccbc",
        textColor: "#000000",
        bgColor: "#ffccbc",
      },
      {
        title: "Deep Orange 200",
        value: "#ffab91",
        textColor: "#000000",
        bgColor: "#ffab91",
      },
      {
        title: "Deep Orange 300",
        value: "#ff8a65",
        textColor: "#000000",
        bgColor: "#ff8a65",
      },
      {
        title: "Deep Orange 400",
        value: "#ff7043",
        textColor: "#000000",
        bgColor: "#ff7043",
      },
      {
        title: "Deep Orange 500",
        value: "#ff5722",
        textColor: "#ffffff",
        bgColor: "#ff5722",
      },
      {
        title: "Deep Orange 600",
        value: "#f4511e",
        textColor: "#ffffff",
        bgColor: "#f4511e",
      },
      {
        title: "Deep Orange 700",
        value: "#e64a19",
        textColor: "#ffffff",
        bgColor: "#e64a19",
      },
      {
        title: "Deep Orange 800",
        value: "#d84315",
        textColor: "#ffffff",
        bgColor: "#d84315",
      },
      {
        title: "Deep Orange 900",
        value: "#bf360c",
        textColor: "#ffffff",
        bgColor: "#bf360c",
      },
      {
        title: "Deep Orange a100",
        value: "#ff9e80",
        textColor: "#000000",
        bgColor: "#ff9e80",
      },
      {
        title: "Deep Orange a200",
        value: "#ff6e40",
        textColor: "#000000",
        bgColor: "#ff6e40",
      },
      {
        title: "Deep Orange a400",
        value: "#ff3d00",
        textColor: "#ffffff",
        bgColor: "#ff3d00",
      },
      {
        title: "Deep Orange a700",
        value: "#dd2c00",
        textColor: "#ffffff",
        bgColor: "#dd2c00",
      },
      {
        title: "Brown 50",
        value: "#efebe9",
        textColor: "#000000",
        bgColor: "#efebe9",
      },
      {
        title: "Brown 100",
        value: "#d7ccc8",
        textColor: "#000000",
        bgColor: "#d7ccc8",
      },
      {
        title: "Brown 200",
        value: "#bcaaa4",
        textColor: "#000000",
        bgColor: "#bcaaa4",
      },
      {
        title: "Brown 300",
        value: "#a1887f",
        textColor: "#000000",
        bgColor: "#a1887f",
      },
      {
        title: "Brown 400",
        value: "#8d6e63",
        textColor: "#000000",
        bgColor: "#8d6e63",
      },
      {
        title: "Brown 500",
        value: "#795548",
        textColor: "#ffffff",
        bgColor: "#795548",
      },
      {
        title: "Brown 600",
        value: "#6d4c41",
        textColor: "#ffffff",
        bgColor: "#6d4c41",
      },
      {
        title: "Brown 700",
        value: "#5d4037",
        textColor: "#ffffff",
        bgColor: "#5d4037",
      },
      {
        title: "Brown 800",
        value: "#4e342e",
        textColor: "#ffffff",
        bgColor: "#4e342e",
      },
      {
        title: "Brown 900",
        value: "#3e2723",
        textColor: "#ffffff",
        bgColor: "#3e2723",
      },
      {
        title: "Gray 50",
        value: "#eceff1",
        textColor: "#000000",
        bgColor: "#eceff1",
      },
      {
        title: "Gray 100",
        value: "#cfd8dc",
        textColor: "#000000",
        bgColor: "#cfd8dc",
      },
      {
        title: "Gray 200",
        value: "#b0bec5",
        textColor: "#000000",
        bgColor: "#b0bec5",
      },
      {
        title: "Gray 300",
        value: "#90a4ae",
        textColor: "#000000",
        bgColor: "#90a4ae",
      },
      {
        title: "Gray 400",
        value: "#78909c",
        textColor: "#000000",
        bgColor: "#78909c",
      },
      {
        title: "Gray 500",
        value: "#607d8b",
        textColor: "#ffffff",
        bgColor: "#607d8b",
      },
      {
        title: "Gray 600",
        value: "#546e7a",
        textColor: "#ffffff",
        bgColor: "#546e7a",
      },
      {
        title: "Gray 700",
        value: "#455a64",
        textColor: "#ffffff",
        bgColor: "#455a64",
      },
      {
        title: "Gray 800",
        value: "#37474f",
        textColor: "#ffffff",
        bgColor: "#37474f",
      },
      {
        title: "Gray 900",
        value: "#263238",
        textColor: "#ffffff",
        bgColor: "#263238",
      },
    ],
  },
  {
    groupTitle: "Pokémon Colors",
    colors: [
      {
        title: "Bug",
        value: "#a8b821",
        textColor: "#000000",
        bgColor: "#a8b821",
      },
      {
        title: "Dark",
        value: "#6f5848",
        textColor: "#ffffff",
        bgColor: "#6f5848",
      },
      {
        title: "Dragon",
        value: "#7038f9",
        textColor: "#ffffff",
        bgColor: "#7038f9",
      },
      {
        title: "Electric",
        value: "#f8d030",
        textColor: "#000000",
        bgColor: "#f8d030",
      },
      {
        title: "Fairy",
        value: "#ffaec9",
        textColor: "#000000",
        bgColor: "#ffaec9",
      },
      {
        title: "Fighting",
        value: "#c03028",
        textColor: "#ffffff",
        bgColor: "#c03028",
      },
      {
        title: "Fire",
        value: "#f07f2f",
        textColor: "#000000",
        bgColor: "#f07f2f",
      },
      {
        title: "Flying",
        value: "#a890f0",
        textColor: "#000000",
        bgColor: "#a890f0",
      },
      {
        title: "Ghost",
        value: "#715899",
        textColor: "#ffffff",
        bgColor: "#715899",
      },
      {
        title: "Grass",
        value: "#78c750",
        textColor: "#000000",
        bgColor: "#78c750",
      },
      {
        title: "Ground",
        value: "#debf67",
        textColor: "#000000",
        bgColor: "#debf67",
      },
      {
        title: "Ice",
        value: "#98d8d8",
        textColor: "#000000",
        bgColor: "#98d8d8",
      },
      {
        title: "Normal",
        value: "#a9a878",
        textColor: "#000000",
        bgColor: "#a9a878",
      },
      {
        title: "Poison",
        value: "#a040a1",
        textColor: "#ffffff",
        bgColor: "#a040a1",
      },
      {
        title: "Psychic",
        value: "#f85788",
        textColor: "#ffffff",
        bgColor: "#f85788",
      },
      {
        title: "Rock",
        value: "#b89f38",
        textColor: "#ffffff",
        bgColor: "#b89f38",
      },
      {
        title: "Steel",
        value: "#b8b8d0",
        textColor: "#000000",
        bgColor: "#b8b8d0",
      },
      {
        title: "Water",
        value: "#6890f0",
        textColor: "#000000",
        bgColor: "#6890f0",
      },
    ],
  },
]
